spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: xiaoma
    password: 555dedd+5
    url: jdbc:mysql://49.234.18.154/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell
wechat:
  mpAppId: wx0be1e1549c033f06
  mpAppSecret: 761f5d4128fac7f21e83298383eaecf9